/* Copy EN: faithful translation of pl.ts (the strategy document, 1:1 in structure and hierarchy). */
import type { Content } from './types';

export const en: Content = {
  lang: 'en',
  paths: {
    home: '/en/',
    work: '/en/work/',
    studio: '/en/studio/',
    contact: '/en/contact/',
    branding: '/en/services/branding/',
    web: '/en/services/websites/',
    graphic: '/en/services/graphic-design/',
    automation: '/en/services/automation/',
    ai: '/en/services/ai/',
  },
  system: {
    skip: 'Skip to content',
    navLabel: 'Main navigation',
    langLabel: 'Language',
    menu: 'Menu',
    close: 'Close',
    motionPause: 'Pause motion',
    motionPlay: 'Play motion',
    placeholder: 'To be filled in',
    notFound: 'This page is not here.',
    backHome: 'Back to the home page',
    exampleLabel: 'Example of our work',
    proofLabel: 'Client quotes',
  },

  nav: {
    links: [
      { label: 'Work', page: 'work' },
      { label: 'Services', page: 'home', hash: 'uslugi' },
      { label: 'Studio', page: 'studio' },
    ],
    cta: "Let's talk about your project",
  },

  home: {
    meta: {
      title: 'Nest Studio: brand, website and technology studio',
      description: 'We create brands, websites and graphic design, and connect design with automation and AI. Meet Nest Studio and our work.',
    },
    hero: {
      eyebrow: 'Brand and technology studio',
      title: ['A distinct brand.', 'A smoother operation.'],
      lead: 'We design visual identities, websites and materials that show who a company is. We connect them with automation and AI, so good design helps in everyday work too.',
      ctaPrimary: "Let's talk about your project",
      ctaSecondary: 'See our work',
      micro: 'Have a clear brief, or still looking for a direction? We can start from either.',
    },
    work: {
      eyebrow: 'Selected work',
      title: ['First, see', 'how we design.'],
      lead: 'See how we turn what a company needs into an identity, a website and tools people use every day.',
      cardLink: 'See the project',
      all: 'All work',
    },
    proof: {
      items: [
        { quote: '[An authentic client statement describing a specific change or the experience of working together]', name: '[Name and surname]', role: '[Position, company]' },
        { quote: '[An authentic client statement describing a specific change or the experience of working together]', name: '[Name and surname]', role: '[Position, company]' },
        { quote: '[An authentic client statement describing a specific change or the experience of working together]', name: '[Name and surname]', role: '[Position, company]' },
      ],
    },
    direction: {
      eyebrow: 'One direction',
      title: ['What people see.', 'And what happens next.'],
      body: [
        'A client meets your brand, visits your website and sends an enquiry. Then your team takes over: replies, handing information on, preparing an offer.',
        'We design these pieces with the whole in mind. So that communication stays consistent, the website leads to the right action, and the process does not end at the "Send" button.',
      ],
      items: [
        { n: '01', title: 'Recognition', body: 'A clear brand direction and an identity that expresses it.' },
        { n: '02', title: 'Experience', body: 'A website where the offer is easy to understand and the next step is easy to take.' },
        { n: '03', title: 'Efficiency', body: 'Connected tools and less manual handing over of information.' },
      ],
    },
    services: {
      eyebrow: 'What we do',
      title: ['From brand direction', 'to a working solution.'],
      lead: 'We can take on one area or connect several into one project. We set the scope by what really needs to change.',
    },
    process: {
      eyebrow: 'How we work',
      title: ['A clear direction.', 'Considered decisions.'],
      intro: 'You know what we are working on, what needs your decision and what happens next.',
      outcomeLabel: 'Stage outcome',
      steps: [
        { title: 'Understanding', body: 'We start with the company, its audience and the goal of the project. We check what already works, what gets in the way and what result will mean the job was done well.', outcome: 'An agreed goal, priorities and scope.' },
        { title: 'Direction', body: 'We lay out the structure of the solution. Depending on the project: a brand strategy, a site architecture or a process map. We settle the foundations before the details.', outcome: 'An approved direction and delivery plan.' },
        { title: 'Design and build', body: 'We design, show each stage and collect feedback. Then we build the solution and test it against the agreed scenarios.', outcome: 'A finished, tested solution.' },
        { title: 'Handover and growth', body: 'We hand over the materials, access and instructions in scope. We agree what to watch after launch and what further support could look like.', outcome: 'A clear way to use the solution and a plan for next steps.' },
      ],
    },
    studio: {
      eyebrow: 'Studio',
      title: ['We think in wholes.', 'We refine the details.'],
      body: [
        'Nest Studio is a studio that brings together branding, digital design and technology.',
        'Presentation day is only the start. We check how the project works after launch: whether the brand stays consistent, whether the website can grow, and whether the team can use the new tools.',
      ],
      link: 'Meet the studio',
      photoAlt: '[A real photo of the team or the people running the studio, captioned with names and roles]',
    },
    faq: {
      title: 'Before we start.',
      items: [
        { q: 'Do I need to know exactly what I need?', a: 'No. You can come with a ready brief or describe the situation you want to change. At the start we work out whether you need a new identity, a website, a tidier process or a mix of these.' },
        { q: 'Can I order just one service?', a: 'Yes. We can design only the website, extend an existing identity or automate one chosen process. Not every project needs everything changed.' },
        { q: 'How much does it cost?', a: 'We quote once the goal and scope are agreed. What matters includes the number of materials or views, complexity, integrations and the scope of the build. Before we start, you receive a description of the work and its cost.' },
        { q: 'How long does a project take?', a: 'The schedule depends on scope, availability of materials and the number of decision points. We set the timeline before we start, including time for feedback, testing and getting ready to publish.' },
        { q: 'Do you work with an existing identity or website?', a: 'Yes. First we check what is worth keeping. We can extend the current system, tidy up chosen parts or propose a bigger change if it is justified.' },
        { q: 'What will I get at the end?', a: 'The materials and access defined in the project scope. Depending on the service: identity files, guidelines, templates, a live website, integration documentation and a user guide. Rights, licences and handover terms are agreed before we start.' },
        { q: 'Does every improvement need AI?', a: 'No. We look at the task first. If a simpler integration or rule-based automation is enough, that is what we propose.' },
        { q: 'Can you support us after launch?', a: 'We can agree a separate scope for further development, updates or support. Its terms depend on the solution and on what your team needs.' },
      ],
    },
    cta: {
      title: ['What do you want to change', 'in your company?'],
      body: 'Your image, your website, the way you work, or several things at once? Tell us where you are and what you need. That is where we start.',
      button: "Let's talk about your project",
      mailPrefix: 'Prefer email? Write to',
    },
  },

  services: [
    {
      id: 'branding',
      name: 'Branding',
      object: 'skaner',
      meta: { title: 'Branding and visual identity | Nest Studio', description: 'Strategy, visual identity and a consistent brand system. See how Nest Studio turns a company’s character into considered design.' },
      card: { title: 'A brand with its own character.', body: 'We sort out what you want to say, to whom, and why they should choose you. Then we turn that direction into a visual identity and rules your team can use every day.', scope: ['Brand strategy', 'Visual identity', 'Brand system', 'Guidelines'], link: 'Explore branding' },
      page: {
        title: ['A brand with character.', 'Not just a logo.'],
        lead: 'We help define what sets your company apart and give it form. We create identities that work as a system: on the website, in a presentation and in everyday communication.',
        blocks: [
          { label: 'When to start', title: ['The company has changed.', 'Has the brand kept up?'], body: ['You are growing the offer, reaching new audiences or entering another market. Meanwhile the identity still tells the story of the company from a few years ago. We help decide what to keep, what to tidy up and what to take in a new direction.'] },
          { label: 'What we design', list: [
            { term: 'Brand direction', text: 'audiences, positioning, differentiators and key messages.' },
            { term: 'Visual identity', text: 'mark, typography, colour and graphic language.' },
            { term: 'System of applications', text: 'layouts, rules and examples of use at key touchpoints.' },
            { term: 'Guidelines', text: 'organised documentation for the team and future contractors.' },
          ] },
          { label: 'What stays after the project', body: ['You get an agreed set of materials and rules. With them, new formats look like the same brand, even when someone else makes them.'] },
        ],
        related: { text: 'A new brand needs a good home online.', link: 'See how we design websites', to: 'web' },
      },
    },
    {
      id: 'web',
      name: 'Websites',
      object: 'kostka',
      meta: { title: 'Website design and development | Nest Studio', description: 'We design and build websites: structure, content, UX/UI, CMS and integrations. Meet the Nest Studio approach.' },
      card: { title: 'A website with a clear job.', body: 'We design and build websites where it is clear at once what you offer and what to click next. From structure and content to interface, build and integrations.', scope: ['UX/UI', 'Structure and content', 'Development', 'CMS', 'Integrations'], link: 'Explore websites' },
      page: {
        title: ['It looks good.', 'And it is clear what to do next.'],
        lead: 'We design websites that present the offer clearly, show the company is credible and lead to contact, a purchase or another defined goal. We combine content, UX, design and build.',
        blocks: [
          { label: 'Starting point', title: ['We start with the job.', 'Not with a layout of sections.'], body: ['What is the user looking for? What do they need to understand before deciding? Which questions stop them from getting in touch? We build the structure of the website on these answers.'] },
          { label: 'Scope', list: [
            { term: 'Architecture and content', text: 'order of information, subpages and key messages.' },
            { term: 'UX/UI', text: 'user paths, views and interface components.' },
            { term: 'Build', text: 'a responsive website and configuration of the agreed features.' },
            { term: 'CMS', text: 'content editing in the areas agreed in the project.' },
            { term: 'Integrations', text: 'forms, CRM and other tools you need.' },
            { term: 'Ready to grow', text: 'technical SEO basics and configuration of the agreed measurements.' },
          ] },
          { label: 'After launch', body: ['Publishing is when the website starts working. We agree what is worth measuring and which parts can be developed later based on how people actually use it.'] },
        ],
        related: { text: 'What happens after the form is sent?', link: 'Explore process automation', to: 'automation' },
      },
    },
    {
      id: 'graphic',
      name: 'Graphic design',
      object: 'splot',
      meta: { title: 'Graphic design for companies | Nest Studio', description: 'Presentations, sales materials, campaigns and templates. Graphic design that extends your brand’s language.' },
      card: { title: 'Consistent in every format.', body: 'We extend the brand language into presentations, campaigns, sales materials and digital communication. We also build templates your team can work with on its own.', scope: ['Presentations', 'Sales materials', 'Campaigns', 'Social media', 'Templates'], link: 'Explore graphic design' },
      page: {
        title: ['One visual language.', 'Many uses.'],
        lead: 'We design materials that build on the brand’s character instead of reinventing it every time. From presentations and offers to campaigns and everyday communication.',
        blocks: [
          { label: 'Starting point', title: ['Each piece on its own terms.', 'All of them as one brand.'], body: ['A sales deck, an ad and a document for a client have different jobs. We design them to meet those needs while keeping a shared visual language.'] },
          { label: 'Scope', list: [
            { text: 'Company and sales presentations.' },
            { text: 'Offers, reports, catalogues and publications.' },
            { text: 'Key visuals for campaigns.' },
            { text: 'Advertising materials and social media communication.' },
            { text: 'Templates for self-editing.' },
            { text: 'Selected print materials.' },
          ] },
          { label: 'How we work together', body: ['We can prepare a defined set of materials or agree an ongoing scope of support. Either way, we agree priorities, formats and how tasks are handed over.'] },
        ],
        related: { text: 'Missing the rules that tie all materials together?', link: 'Explore branding', to: 'branding' },
      },
    },
    {
      id: 'automation',
      name: 'Process automation',
      object: 'przeplyw',
      meta: { title: 'Process automation and integrations | Nest Studio', description: 'We tidy up repetitive tasks and connect company tools. Explore process automation designed by Nest Studio.' },
      card: { title: 'Less copy and paste. More getting things done.', body: 'We connect tools and tidy up repetitive tasks. We design how information flows between forms, CRM, email and the other systems your company uses.', scope: ['Process analysis', 'Integrations', 'Information flow', 'Notifications', 'Reporting'], link: 'Explore automation' },
      page: {
        title: ['Fewer manual steps.', 'More order in your work.'],
        lead: 'We help reduce repetitive tasks and connect tools that today need data moved by hand. We start with the process and only then choose the technology.',
        blocks: [
          { label: 'Starting point', title: ['What in your company', 'keeps getting done twice?'], body: ['Retyping enquiries. Updating several systems. Passing on the same information. Reminding people of the next step. Together we check which of these can be simplified and how to handle the unusual cases.'] },
          { label: 'Example uses', list: [
            { text: 'Passing enquiries from the website to the CRM.' },
            { text: 'Creating tasks and notifications for the right people.' },
            { text: 'Syncing agreed data between tools.' },
            { text: 'Preparing documents from approved templates.' },
            { text: 'Summaries and recurring reports.' },
          ] },
          { label: 'How we approach the build', body: ['We describe the current process, choose a part to improve and test the solution. We also agree how errors are monitored, who is responsible for maintenance and what should happen when the automation cannot complete a task.'] },
          { label: 'Measure of success', body: ['Before the build we set a baseline, for example the time to handle a case or the number of manual steps. After launch we can check whether the change delivered the expected result.'] },
        ],
        related: { text: 'Does the process need work with content or company knowledge?', link: 'Explore AI solutions', to: 'ai' },
      },
    },
    {
      id: 'ai',
      name: 'AI solutions',
      object: 'siatka',
      meta: { title: 'AI solutions for companies | Nest Studio', description: 'We check where AI can support your team. Use-case analysis, prototypes and integrations fitted to a specific task.' },
      card: { title: 'AI with a specific job.', body: 'We check where AI can support your team: finding knowledge, analysing documents, preparing replies. We start with the use case and tests, not with the promise that AI will do everything.', scope: ['Use-case analysis', 'Prototypes', 'Knowledge assistants', 'Document work', 'Integrations'], link: 'Explore AI solutions' },
      page: {
        title: ['Not AI for everything.', 'AI for a specific task.'],
        lead: 'We design and test AI applications embedded in the real work of a company. From finding information in documents to preparing materials for the team to review.',
        blocks: [
          { label: 'Starting point', title: ['The use case first.', 'Then the model.'], body: ['We start with what should change: the time spent finding information, the way documents are analysed or how replies are prepared. We agree what quality you expect and where a human decision is needed.'] },
          { label: 'Example areas', list: [
            { text: 'Assistants that use an organised knowledge base.' },
            { text: 'Finding and organising information from documents.' },
            { text: 'First-pass classification of enquiries.' },
            { text: 'Summaries and working drafts.' },
            { text: 'Support for internal service and communication processes.' },
          ] },
          { label: 'From prototype to decision', body: ['We build a limited prototype and test it on agreed examples. We assess how useful the answers are, the costs, the limits and how errors are handled. Only then do we recommend a further build, a change of approach or a simpler solution.'] },
          { label: 'Working principles', body: ['Before the build we agree the scope of data, permissions, rules for using providers and the points that need human review. We do not promise perfection or full autonomy.'] },
        ],
      },
    },
  ],

  projects: [
    {
      id: 'perun-tac',
      name: 'Perun Tac',
      sentence: '[One sentence describing the real goal or change in the project.]',
      tags: ['Branding', 'Website'],
      year: '2026',
      status: '',
      image: '/v2/work/perun-tac.webp',
      alt: 'Perun Tac home page: two divisions side by side, training and protection',
      href: 'https://peruntac.pl',
      services: ['branding', 'web'],
    },
    {
      id: 'oboda-group',
      name: 'Oboda Group',
      sentence: 'An organised offer and a new way of presenting services.',
      tags: ['Strategy', 'Website'],
      year: '2026',
      status: '[Status to confirm]',
      image: '/v2/work/oboda-group.webp',
      alt: 'Oboda Group home page: yellow background, a headline about training receptionists and a photo of the trainer',
      href: '',
      services: ['web'],
    },
    {
      id: 'tcc-global',
      name: 'TCC Global',
      sentence: '[One sentence describing the real goal or change in the project.]',
      tags: ['Website'],
      year: '2026',
      status: 'Concept project',
      image: '',
      alt: '',
      href: '',
      services: ['web'],
    },
  ],

  workPage: {
    meta: { title: 'Work: branding, websites and technology | Nest Studio', description: 'See selected identities, websites and solutions. We show the starting point, the direction of the work and what came out of it. Not just the final mockup.' },
    title: ['Projects backed by', 'specific decisions.'],
    lead: 'See selected identities, websites and solutions. We show the starting point, the direction of the work and what came out of it. Not just the final mockup.',
  },

  studioPage: {
    meta: { title: 'Meet our studio | Nest Studio', description: 'Nest Studio brings together branding, design and technology. We put company images in order, build their websites and improve chosen areas of their work.' },
    title: ['Real people', 'behind every project.'],
    lead: 'Nest Studio brings together branding, design and technology. We put company images in order, build their websites and improve chosen areas of their work.',
    approach: {
      label: 'Our approach',
      title: ['Good design still makes sense', 'after the presentation.'],
      body: [
        'An identity has to be easy to develop consistently. A website has to say clearly what you offer. An automation has to handle the exceptions, not just the ideal scenario.',
        'That is what quality means to us: a good idea, solid execution and something the team actually uses.',
      ],
    },
    principlesTitle: 'Three principles',
    principles: [
      { title: 'Understanding first', body: 'We do not start with a ready answer. First we learn the context and the constraints.' },
      { title: 'Decisions with reasons', body: 'With every solution we give the reason we propose it.' },
      { title: 'Whole and detail', body: 'We keep the shared direction without losing sight of a single view, sentence or interaction.' },
    ],
    peopleTitle: 'People',
    people: [
      { name: 'Filip Jakubiak', role: '[Role]', bio: '[Two specific sentences about responsibilities and experience.]', placeholder: true },
    ],
  },

  contactPage: {
    meta: { title: "Let's talk about your project | Nest Studio", description: 'Briefly describe your company, idea or problem. We will agree what the next step should be.' },
    title: ["Let's start with", 'what you need.'],
    lead: 'Briefly describe your company, idea or problem. You do not need a finished specification. From there we will agree what the next step should be.',
    required: 'Fields marked * are required.',
    fields: {
      name: { label: 'Name', hint: 'What should we call you?' },
      email: { label: 'Email', hint: 'We will reply to this address.' },
      message: { label: 'About the project', hint: 'What do you want to create or change? What is the biggest challenge today?' },
      company: { label: 'Company or current website' },
      scope: { label: 'Scope', options: ['Branding', 'Website', 'Graphic design', 'Automation', 'AI', 'Not sure yet'] },
      budget: { label: 'Planned budget', options: ['[range 1]', '[range 2]', '[range 3]', 'I need help deciding'] },
      timing: { label: 'Preferred timing' },
    },
    optional: 'optional',
    submit: 'Send enquiry',
    privacy: 'You will find how we process data in the Privacy policy.',
    nextTitle: 'What happens next?',
    next: ['We read your message.', 'We come back with questions or a proposal for a call.', 'If the scope fits what we do, we agree how to prepare an offer.'],
    sentTitle: 'Thank you. Your message has arrived.',
    sentBody: 'We will read your description and get back to the address you gave. If you want to add something, write to [E-MAIL].',
    sentLink: 'Back to our work',
    errorBody: 'The message could not be sent. Try again or write directly to [E-MAIL]. What you typed stays in the form.',
    mailSubject: 'Enquiry from the Nest Studio website',
  },

  footer: {
    tagline: ['Branding, websites and technology.', 'Designed with the whole in mind.'],
    cols: [
      { title: 'Explore', links: [{ label: 'Work', page: 'work' }, { label: 'Services', page: 'home', hash: 'uslugi' }, { label: 'Studio', page: 'studio' }, { label: 'Contact', page: 'contact' }] },
      { title: 'Services', links: [{ label: 'Branding', page: 'branding' }, { label: 'Websites', page: 'web' }, { label: 'Graphic design', page: 'graphic' }, { label: 'Automation', page: 'automation' }, { label: 'AI', page: 'ai' }] },
    ],
    contactTitle: 'Contact',
    location: '[Location, if relevant]',
    socialTitle: 'Profiles',
    legal: '[Full legal name]',
    privacy: 'Privacy policy',
    cookies: 'Cookie settings',
  },
};
