import type { Content } from './types';

/* English adaptation (not a literal translation). Strategy and rationale: docs/copy.md. */
export const en: Content = {
  lang: 'en',
  meta: {
    title: 'Nest Studio: branding, websites and AI automation',
    description: "Filip Jakubiak's design studio, since 2014. Brand strategy, identity, websites and AI automation from one studio, with no loose ends.",
    ogTitle: 'We design brands and build everything that holds them together.',
  },
  nav: {
    links: [
      { label: 'Work', href: '#projekty' },
      { label: 'Services', href: '#uslugi' },
      { label: 'Process', href: '#proces' },
      { label: 'Studio', href: '#studio' },
      { label: 'Contact', href: '#kontakt' },
    ],
    cta: 'Start a project',
    langLabel: 'Change language',
    menu: 'Menu',
    closeMenu: 'Close menu',
    remote: 'Remote, from Poland',
  },
  preloader: { loading: 'Loading' },
  hero: {
    eyebrow: 'Design studio, since 2014',
    lines: ['We design brands', 'and build everything', 'that holds them together.'],
    dropAfterLine: 1,
    lead: 'Strategy, identity, website and AI automation, all from one studio. No loose ends.',
    ctaPrimary: 'Start a project',
    ctaSecondary: 'See the work',
  },
  tension: {
    title: "The company grew. Its image didn't.",
    leftLabel: 'how you are seen',
    leftWord: 'Looks',
    rightLabel: 'what you are worth',
    rightWord: 'Worth',
    you: 'A logo from year one. A three-year-old website. Proposals in Word.',
    body: 'Each part was made by someone else, at a different time, so nothing matches. A client sees it before reading a word of your proposal. That gap has a price: trust, rates, and hours spent explaining who you are.',
    closing: ['Loose threads snap.', 'Woven ones hold.'],
  },
  showreel: {
    eyebrow: 'Showreel, rendered live',
    title: 'This is not a video.',
    lead: 'Everything you see here is rendered live, in your browser. Your scroll is the scrubber.',
    cuts: [
      { label: 'Type', line: 'Letters instead of footage.' },
      { label: 'Chrome', line: 'Metal that never cools.' },
      { label: 'Threads', line: 'From tangle to weave.' },
      { label: 'Web', line: 'The site is the proof.' },
      { label: 'Automation', line: 'An engine room in plain sight.' },
    ],
    play: 'Play',
    pause: 'Pause',
    playAria: 'Play showreel',
    pauseAria: 'Pause showreel',
  },
  projects: {
    title: 'Selected work',
    lead: 'What needed doing, and what we did. Full case studies on a call.',
    askLink: 'Ask for the full case study',
    items: [
      { slug: 'perun-tac', name: 'Perun Tac', scope: ['Branding', 'Website', 'CMS'], metric: '3', metricLabel: 'editors run the site from their own panel', year: '2026', summary: 'Firearms and tactical training in Wrocław. A bilingual website and a panel where the team publishes courses and dates on its own.', seed: 11, placeholder: true },
      { slug: 'tcc-global', name: 'TCC Global', scope: ['Website', 'Motion'], metric: '2', metricLabel: 'directions for the new site, ready to choose', year: '2026', summary: 'Loyalty programmes for grocery retailers and brands. A new website told through motion, in two directions for the board to decide on.', seed: 23, placeholder: true },
      { slug: 'oboda-group', name: 'Oboda Group', scope: ['Redesign', 'Content architecture'], metric: '9 → 5', metricLabel: 'categories turned into paths by role', year: '2026', summary: 'Training and consulting for dentistry. A concept for a new site where dentists, assistants and practice owners each land on their own offer.', seed: 37, placeholder: true },
    ],
  },
  services: {
    eyebrow: 'Services',
    title: 'Four threads. One weave.',
    items: [
      { id: 'strategy', title: 'Brand strategy', body: 'Positioning, messaging, brand architecture. We settle what you say, to whom, and why it should be you. Only then do we draw.' },
      { id: 'brand', title: 'Branding', body: 'Mark, type, colour, rules and ready files. A system your team can use from day one without calling us.' },
      { id: 'web', title: 'Websites', body: 'Design and code by the same hands. Fast, accessible, with motion only where it explains something. This site is the sample.' },
      { id: 'ai', title: 'AI and automation', body: 'Inquiries, proposals, invoices, customer support. AI flows wired into the tools you already use. A person approves, the machine does the rest.' },
    ],
    note: 'Each thread can be taken on its own. They hold best woven together.',
  },
  aiDemo: {
    title: 'Automation you can watch.',
    lead: 'Pick a process someone on your team still does by hand, and run the flow.',
    run: 'Run the flow',
    status: { ready: 'Ready', running: 'Running', done: 'Done' },
    note: 'The demo runs on sample data. In a real deployment we connect the flow to your tools.',
    nodeLabels: { trigger: 'Trigger', read: 'Read', classify: 'Classify', draft: 'Draft', review: 'Review', crm: 'CRM', email: 'Email', document: 'Document', calendar: 'Calendar', notify: 'Notify' },
    logAria: 'Flow log',
    presets: [
      { id: 'inquiry', label: 'Form inquiry', steps: [
        { node: 'trigger', text: 'New form submission' },
        { node: 'classify', text: 'Sorted: sales, support or spam' },
        { node: 'crm', text: 'CRM entry with a short summary' },
        { node: 'draft', text: 'Reply drafted in your brand voice' },
        { node: 'notify', text: 'Notification with one button: send' },
      ] },
      { id: 'invoice', label: 'New invoice', steps: [
        { node: 'trigger', text: 'Invoice arrives by email' },
        { node: 'read', text: 'Data read: vendor, amount, due date' },
        { node: 'review', text: 'Matched to the purchase order' },
        { node: 'document', text: 'Posted to accounting' },
        { node: 'calendar', text: 'Reminder before the due date' },
      ] },
      { id: 'proposal', label: 'Client proposal', steps: [
        { node: 'trigger', text: 'Meeting notes' },
        { node: 'read', text: 'Scope and assumptions pulled from the notes' },
        { node: 'draft', text: 'Proposal drafted on your template' },
        { node: 'review', text: 'Prices and dates checked' },
        { node: 'document', text: 'Document waiting for your approval' },
      ] },
      { id: 'social', label: 'Social media post', steps: [
        { node: 'trigger', text: 'New project in the portfolio' },
        { node: 'draft', text: 'Three post drafts in the brand voice' },
        { node: 'read', text: 'Visual picked from the brand system' },
        { node: 'calendar', text: 'Post added to the publishing queue' },
        { node: 'notify', text: 'Results summary after a week' },
      ] },
    ],
  },
  process: {
    title: 'One thread, five stages.',
    steps: [
      { title: 'Conversation', body: 'About the company, your clients and what eats most of your time. Afterwards you get a written scope and quote.' },
      { title: 'Strategy', body: 'Positioning and messaging on a few pages. Later, that document settles every argument about a colour or a word.' },
      { title: 'Design', body: 'Identity and website design. We show directions, choose one and refine it with you.' },
      { title: 'Build', body: 'Code, content, launch. The site is built where it was designed, so nothing gets lost in the handover.' },
      { title: 'Engine room', body: 'Automation and AI wired into your tools. We launch it, train the team and stay on for support.' },
    ],
  },
  studio: {
    title: 'You talk to the person who does the work.',
    p1: "I'm Filip Jakubiak, and I have been designing since 2014. I started with identity, then came websites, and now automation and AI as well. I do them together, because apart they drift.",
    p2: 'I work alone or with a small team picked for the project. No account manager, no brief passed down the line. The person you talk to is the person who designs.',
    years: '{years} years in the field',
    since: 'since 2014',
    photoAlt: 'Filip Jakubiak, Nest Studio',
    photoPlaceholder: 'photo',
  },
  faq: {
    title: 'Before you write',
    items: [
      { q: 'How much does a project cost?', a: 'As much as the scope requires, which is why you get a written quote after the first call. One quote covers everything we agree on: strategy, identity, website and automation.' },
      { q: 'How long does it take?', a: 'That depends on the scope too. You get a schedule with real dates together with the quote, before any work starts.' },
      { q: 'Why one studio, when I already have a designer and a developer?', a: 'Because most things break at the handover. The designer sends files, the developer does it their way, and someone else bolts on the automation. When the whole thing is made in one place, there is nothing to drop in between.' },
      { q: 'Can I order just the website or just the automation?', a: 'Yes. Each thread can be taken on its own. We will tell you what is worth adding, and we will take "not now" for an answer.' },
      { q: 'What does working with AI look like in practice?', a: 'We start with one process that takes up the most time today. We build the flow on the tools you already use, test it on real examples and train the team. AI prepares, a person approves.' },
      { q: 'What do I get at the end?', a: 'Source files, the brand system, the website code, access and a description of every flow. All of it is yours.' },
      { q: 'Will my website be as animated as this one?', a: 'Only where motion explains something. This site is a demonstration. Yours has a different job: to sell.' },
      { q: 'Where do you work from?', a: 'Remotely, from Poland, in Polish and English. We meet online, and on site when the project calls for it.' },
    ],
  },
  contact: {
    eyebrow: 'Contact',
    title: "Let's start with the first thread.",
    lead: 'One conversation, no pitch deck, no commitment. Tell us what your company does and what you still do by hand. We will work out the rest together.',
    cta: 'Start a project',
    calendar: 'pick a time in the calendar',
    or: 'or',
  },
  footer: {
    contact: 'Contact',
    data: 'Details',
    social: 'Social',
    ask: 'Ask about Nest Studio',
    askPrompt: "What do you know about Nest Studio, Filip Jakubiak's design studio (neststudio.pl)? What does it do, who does it work for, and what sets it apart?",
    legal: 'Designed and built at Nest Studio.',
    privacy: 'Privacy policy',
    country: 'Poland',
  },
  system: {
    skip: 'Skip to content',
    rail: 'Section navigation',
    reduced: 'Animations are off, following your system settings.',
    noWebgl: 'The 3D scene does not run in this browser. All the content is available without it.',
    notFound: 'This page does not exist.',
    backHome: 'Go back home',
    placeholder: 'to be added',
  },
};
