/* Copy v2 (EN): translation of pl.ts. [brackets] = data to replace (docs/placeholders.md). */
import type { Content } from './types';
import { EMAIL, FOUNDED_YEAR, yearsInField } from './site';

export const en: Content = {
  lang: 'en',
  meta: {
    title: 'Nest Studio: brand, website and technology studio',
    description: 'We create brands, websites and graphic design, and connect design with automation and AI. Meet Nest Studio and our work.',
    ogTitle: 'Nest Studio: a distinct brand, a smoother operation',
  },
  system: {
    skip: 'Skip to content',
    navLabel: 'Main navigation',
    langLabel: 'Language',
    menu: 'Menu',
    close: 'Close',
    motionPause: 'Pause motion',
    motionPlay: 'Play motion',
    placeholder: 'To be filled in',
    notFound: 'This page is not here.',
    backHome: 'Back to the home page',
  },
  nav: {
    links: [
      { label: 'Work', href: '#realizacje' },
      { label: 'Services', href: '#uslugi' },
      { label: 'Studio', href: '#studio' },
      { label: 'Contact', href: '#kontakt' },
    ],
    cta: "Let's talk about your project",
  },
  hero: {
    eyebrow: 'Brand and technology studio',
    title: ['A distinct brand.', 'A smoother operation.'],
    lead: 'We create visual identities, websites and materials that give companies a consistent character. We connect them with automation and AI, so good design pays off in everyday work.',
    ctaPrimary: "Let's talk about your project",
    ctaSecondary: 'See our work',
    micro: 'Have a clear brief, or still looking for a direction? We can start from either.',
  },
  stats: {
    eyebrow: 'In numbers',
    items: [
      { value: String(FOUNDED_YEAR), label: 'the year we started designing', placeholder: false },
      { value: String(yearsInField(2026)), label: 'years in the field', placeholder: false },
      { value: '5', label: 'areas, from brand to AI', placeholder: false },
      { value: '[00]', label: '[projects delivered]', placeholder: true },
    ],
    note: 'We only count what can be checked.',
  },
  who: {
    eyebrow: 'One direction',
    title: ['What people see.', 'And what happens next.'],
    body: [
      'A client meets your brand, visits your website and sends an enquiry. Then your team takes over: replies, handing information on, preparing an offer.',
      'We design these pieces as one whole. Like threads in a weave: each holds because the rest holds it. Communication stays consistent, the website leads to the right action, and the process does not end at the "Send" button.',
    ],
    pillars: [
      { n: '01', title: 'Recognition', body: 'A clear brand direction and an identity that expresses it.' },
      { n: '02', title: 'Experience', body: 'A website where the offer is easy to understand and the next step is easy to take.' },
      { n: '03', title: 'Efficiency', body: 'Connected tools and less manual handing over of information.' },
    ],
  },
  work: {
    eyebrow: 'Selected work',
    title: ['First, see', 'how we design.'],
    lead: 'Different companies, different challenges. See how we turn business needs into an identity, a website and solutions ready for everyday use.',
    projects: [
      {
        id: 'perun-tac',
        name: 'Perun Tac',
        sentence: 'Two divisions, training and protection, in one brand. A website with its own content panel that the team edits itself.',
        tags: ['Branding', 'Website', 'CMS'],
        year: '2026',
        status: 'Live',
        image: '/v2/work/perun-tac.webp',
        alt: 'Perun Tac home page: two divisions side by side, training and protection',
        href: 'https://peruntac.pl',
        linkLabel: 'Visit the site',
      },
      {
        id: 'oboda-group',
        name: 'Oboda Group',
        sentence: 'Training for dental practices, organised by the roles in the team rather than by price-list categories.',
        tags: ['Redesign', 'Offer architecture', 'Website'],
        year: '2026',
        status: '[Phase 1, to confirm]',
        image: '/v2/work/oboda-group.webp',
        alt: 'Oboda Group home page: yellow background, a headline about training receptionists and a photo of the trainer',
        href: '',
        linkLabel: '',
      },
      {
        id: 'tcc-global',
        name: 'TCC Global',
        sentence: 'A proposal for a new website for a global company, prepared and presented to the board.',
        tags: ['Website', 'Motion', 'Presentation'],
        year: '2026',
        status: 'Concept project',
        image: '',
        alt: '',
        href: '',
        linkLabel: '',
      },
    ],
    all: 'All work',
  },
  services: {
    eyebrow: 'What we do',
    title: ['From brand direction', 'to a working solution.'],
    lead: 'We can take on one area or connect several into one coherent project. We set the scope by what really needs to change.',
    items: [
      { id: 'branding', name: 'Branding', title: 'A brand with its own character.', body: 'We sort out what you want to say, to whom, and why they should choose you. Then we turn that direction into a visual identity and rules your team can use every day.', scope: ['Brand strategy', 'Visual identity', 'Brand system', 'Guidelines'], object: 'skaner' },
      { id: 'web', name: 'Websites', title: 'A website with a clear job.', body: 'We design and build websites that show the value of the offer and lead people to the next step. From structure and content to interface, build and integrations.', scope: ['UX/UI', 'Structure and content', 'Development', 'CMS', 'Integrations'], object: 'kostka' },
      { id: 'graphic', name: 'Graphic design', title: 'Consistent in every format.', body: 'We extend the brand language into presentations, campaigns, sales materials and digital communication. We also build templates your team can work with on its own.', scope: ['Presentations', 'Sales materials', 'Campaigns', 'Social media', 'Templates'], object: '' },
      { id: 'automation', name: 'Process automation', title: 'Less copy and paste. More getting things done.', body: 'We connect tools and tidy up repetitive tasks. We design how information flows between forms, CRM, email and the other systems your company uses.', scope: ['Process analysis', 'Integrations', 'Information flow', 'Notifications', 'Reporting'], object: 'przeplyw' },
      { id: 'ai', name: 'AI solutions', title: 'AI with a specific job.', body: 'We check where AI can support your team: finding knowledge, analysing documents, preparing replies. We start with the use case and tests, not with the promise that AI will do everything.', scope: ['Use-case analysis', 'Prototypes', 'Knowledge assistants', 'Document work', 'Integrations'], object: 'siatka' },
    ],
  },
  about: {
    eyebrow: 'Studio',
    title: ['We think in wholes.', 'We refine the details.'],
    body: [
      'Nest Studio brings together branding, digital design and technology.',
      'We care not only about how a project looks on presentation day. It matters just as much how it works after launch: whether the brand stays consistent, whether the website can grow, and whether the team can use the new tools. That is why we tie design decisions to the realities of everyday work.',
    ],
    principles: [
      { title: 'Understanding first', body: 'We do not start with a ready answer. First we learn the context and the constraints.' },
      { title: 'Decisions with reasons', body: 'We show not only the solution but also why we propose it.' },
      { title: 'Whole and detail', body: 'We keep the shared direction without losing sight of a single view, sentence or interaction.' },
    ],
    link: "Let's talk about your project",
  },
  testimonials: {
    eyebrow: 'Testimonials',
    items: [
      { quote: "[An authentic client quote about a specific change or what it was like to work together.]", name: '[Full name]', role: '[Role, company]', placeholder: true },
    ],
  },
  team: {
    eyebrow: 'Team',
    title: ['Real people', 'behind every project.'],
    lead: 'You work directly with the person who runs the project. Trusted specialists join larger scopes.',
    people: [
      { name: 'Filip Jakubiak', role: 'Founder. Branding, websites, automation', bio: `Designing since ${FOUNDED_YEAR}. [Two specific sentences about responsibilities and experience.]`, placeholder: true },
      { name: '[Full name]', role: '[Specialist role]', bio: '[Two specific sentences about responsibilities and experience.]', placeholder: true },
    ],
  },
  process: {
    eyebrow: 'How we work',
    title: ['A clear direction.', 'Considered decisions.'],
    intro: 'You know what we are working on, what needs your decision and what happens next.',
    outcomeLabel: 'Stage outcome',
    steps: [
      { title: 'Understanding', body: 'We start with the company, its audience and the goal of the project. We check what already works, what gets in the way and what result will mean the job was done well.', outcome: 'An agreed goal, priorities and scope.' },
      { title: 'Direction', body: 'We lay out the structure of the solution: a brand strategy, a site architecture or a process map, depending on the project. We settle the foundations before the details.', outcome: 'An approved direction and delivery plan.' },
      { title: 'Design and build', body: 'We design, show each stage and collect feedback. Then we build the solution and test it against the agreed scenarios.', outcome: 'A finished, tested solution.' },
      { title: 'Handover and growth', body: 'We hand over the materials, access and instructions in scope. We agree what to watch after launch and what further support could look like.', outcome: 'A clear way to use the solution and a plan for next steps.' },
    ],
  },
  pricing: {
    eyebrow: 'Pricing',
    title: ['The cost follows', 'the scope.'],
    lead: 'We prepare a quote once the goal and scope are agreed. Before we start, you receive a description of the work and its cost.',
    tiers: [
      { name: 'Brand', price: '[from 0,000 PLN]', body: 'Brand direction and a visual identity with rules of use.', scope: ['Brand strategy', 'Identity', 'Guidelines'] },
      { name: 'Website', price: '[from 0,000 PLN]', body: 'Design and build of a website with content, CMS and integrations.', scope: ['Structure and content', 'UX/UI', 'Build'] },
      { name: 'Brand, website and processes', price: '[individual quote]', body: 'The whole: from brand direction to automated enquiry handling.', scope: ['Branding', 'Website', 'Automation and AI'] },
    ],
    note: 'What matters includes the number of materials or views, complexity, integrations and the scope of the build.',
    faqTitle: 'Before we start.',
    faq: [
      { q: 'Do I need to know exactly what I need?', a: 'No. You can come with a ready brief or describe the situation you want to change. At the start we work out whether you need a new identity, a website, a tidier process or a mix of these.' },
      { q: 'Can I order just one service?', a: 'Yes. We can design only the website, extend an existing identity or automate one chosen process. Not every project needs everything changed.' },
      { q: 'How much does it cost?', a: 'We quote once the goal and scope are agreed. What matters includes the number of materials or views, complexity, integrations and the scope of the build. Before we start, you receive a description of the work and its cost.' },
      { q: 'How long does a project take?', a: 'The schedule depends on scope, availability of materials and the number of decision points. We set the timeline before we start, including time for feedback, testing and getting ready to publish.' },
      { q: 'Do you work with an existing identity or website?', a: 'Yes. First we check what is worth keeping. We can extend the current system, tidy up chosen parts or propose a bigger change if it is justified.' },
      { q: 'What will I get at the end?', a: 'The materials and access defined in the project scope. Depending on the service: identity files, guidelines, templates, a live website, integration documentation and a user guide. Rights, licences and handover terms are agreed before we start.' },
      { q: 'Does every improvement need AI?', a: 'No. We look at the task first. If a simpler integration or rule-based automation is enough, that is what we propose.' },
      { q: 'Can you support us after launch?', a: 'We can agree a separate scope for further development, updates or support. Its terms depend on the solution and on what your team needs.' },
    ],
  },
  partners: {
    eyebrow: 'Clients',
    title: 'Companies we work with',
    names: ['Perun Tac', 'Perun Sec', 'Oboda Group', 'TCC Global', '[Client]', '[Client]'],
    note: 'We show logos with our clients’ consent.',
  },
  cta: {
    title: ['What do you want to change', 'in your company?'],
    body: 'Your image, your website, the way you work, or several things at once? Tell us where you are and what you need. That is where we start.',
    button: "Let's talk about your project",
    mailPrefix: 'Prefer email? Write to',
  },
  contact: {
    eyebrow: 'Contact',
    title: ["Let's start with", 'what you need.'],
    lead: 'Briefly describe your company, idea or problem. You do not need a finished specification. From there we will agree the next step.',
    required: 'Fields marked * are required.',
    fields: {
      name: { label: 'Name', hint: 'What should we call you?' },
      email: { label: 'Email', hint: 'We will reply to this address.' },
      message: { label: 'About the project', hint: 'What do you want to create or change? What is the biggest challenge today?' },
      company: { label: 'Company or current website', hint: '' },
      scope: { label: 'Scope', options: ['Branding', 'Website', 'Graphic design', 'Automation', 'AI', 'Not sure yet'] },
      budget: { label: 'Planned budget', options: ['[range 1]', '[range 2]', '[range 3]', 'I need help deciding'] },
      timing: { label: 'Preferred timing', hint: '' },
    },
    optional: 'optional',
    submit: 'Send enquiry',
    privacy: 'You will find how we process data in the Privacy policy.',
    nextTitle: 'What happens next?',
    next: ['We read your message.', 'We come back with questions or a proposal for a call.', 'If the scope fits what we do, we agree how to prepare an offer.'],
    sentTitle: 'Opening your email.',
    sentBody: `The message is ready to send in your email app. If nothing opened, write to ${EMAIL}.`,
    mailSubject: 'Enquiry from the Nest Studio website',
  },
  footer: {
    tagline: ['Branding, websites and technology.', 'Woven into one whole.'],
    cols: [
      { title: 'Explore', links: [{ label: 'Work', href: '#realizacje' }, { label: 'Services', href: '#uslugi' }, { label: 'Studio', href: '#studio' }, { label: 'Contact', href: '#kontakt' }] },
      { title: 'Services', links: [{ label: 'Branding', href: '#uslugi' }, { label: 'Websites', href: '#uslugi' }, { label: 'Graphic design', href: '#uslugi' }, { label: 'Automation', href: '#uslugi' }, { label: 'AI', href: '#uslugi' }] },
    ],
    contactTitle: 'Contact',
    socialTitle: 'Profiles',
    legal: '[Full legal name]',
    privacy: 'Privacy policy',
    top: 'Back to top',
  },
};
