/* Teksty v2 (PL). Źródło: docs/v2/source/copywriting-strategia.html, wersja Nest: docs/v2/copy.md.
   [nawiasy] = dane do podmiany (docs/placeholders.md). Nic tu nie jest wymyślonym wynikiem. */
import type { Content } from './types';
import { polishTypography } from './typography';
import { EMAIL, FOUNDED_YEAR, yearsInField } from './site';

const raw: Content = {
  lang: 'pl',
  meta: {
    title: 'Nest Studio: studio brandingu, stron internetowych i technologii',
    description: 'Tworzymy marki, strony internetowe i materiały graficzne. Łączymy design z automatyzacjami i AI. Poznaj Nest Studio i nasze realizacje.',
    ogTitle: 'Nest Studio: wyrazista marka, sprawniejsze działanie',
  },
  system: {
    skip: 'Przejdź do treści',
    navLabel: 'Nawigacja główna',
    langLabel: 'Język',
    menu: 'Menu',
    close: 'Zamknij',
    motionPause: 'Zatrzymaj ruch',
    motionPlay: 'Włącz ruch',
    placeholder: 'Do uzupełnienia',
    notFound: 'Tej strony tu nie ma.',
    backHome: 'Wróć na stronę główną',
  },
  nav: {
    links: [
      { label: 'Realizacje', href: '#realizacje' },
      { label: 'Usługi', href: '#uslugi' },
      { label: 'Studio', href: '#studio' },
      { label: 'Kontakt', href: '#kontakt' },
    ],
    cta: 'Porozmawiajmy o projekcie',
  },
  hero: {
    eyebrow: 'Studio brandingu i technologii',
    title: ['Wyrazista marka.', 'Sprawniejsze działanie.'],
    lead: 'Tworzymy identyfikacje wizualne, strony internetowe i materiały, które nadają firmom spójny charakter. Łączymy je z automatyzacjami i AI, żeby dobry projekt miał przełożenie na codzienną pracę.',
    ctaPrimary: 'Porozmawiajmy o projekcie',
    ctaSecondary: 'Zobacz realizacje',
    micro: 'Masz konkretny brief albo dopiero szukasz kierunku? Możemy zacząć od obu.',
  },
  stats: {
    eyebrow: 'W liczbach',
    items: [
      { value: String(FOUNDED_YEAR), label: 'rok, od którego projektujemy', placeholder: false },
      { value: String(yearsInField(2026)), label: 'lat w branży', placeholder: false },
      { value: '5', label: 'obszarów: od marki po AI', placeholder: false },
      { value: '[00]', label: '[zrealizowanych projektów]', placeholder: true },
    ],
    note: 'Liczymy tylko to, co da się sprawdzić.',
  },
  who: {
    eyebrow: 'Jeden kierunek',
    title: ['To, co widać.', 'I to, co dzieje się dalej.'],
    body: [
      'Klient poznaje twoją markę, odwiedza stronę i wysyła zapytanie. Potem zaczyna się praca zespołu: odpowiedzi, przekazywanie informacji, przygotowanie oferty.',
      'Projektujemy te elementy z myślą o całości. Jak nici w splocie: każda trzyma, bo trzyma ją reszta. Komunikacja jest spójna, strona prowadzi do właściwego działania, a proces nie kończy się na kliknięciu „Wyślij”.',
    ],
    pillars: [
      { n: '01', title: 'Rozpoznawalność', body: 'Jasny kierunek marki i identyfikacja, która go wyraża.' },
      { n: '02', title: 'Doświadczenie', body: 'Strona, na której łatwo zrozumieć ofertę i zrobić następny krok.' },
      { n: '03', title: 'Sprawność', body: 'Połączone narzędzia i mniej ręcznego przekazywania informacji.' },
    ],
  },
  work: {
    eyebrow: 'Wybrane realizacje',
    title: ['Najpierw zobacz,', 'jak projektujemy.'],
    lead: 'Różne firmy, różne wyzwania. Zobacz, jak przekładamy potrzeby biznesu na identyfikację, stronę i rozwiązania gotowe do codziennego użycia.',
    projects: [
      {
        id: 'perun-tac',
        name: 'Perun Tac',
        sentence: 'Dwie dywizje, szkolenia i ochrona, w jednej marce. Strona z własnym panelem treści, który zespół edytuje sam.',
        tags: ['Branding', 'Strona internetowa', 'CMS'],
        year: '2026',
        status: 'Wdrożone',
        image: '/v2/work/perun-tac.webp',
        alt: 'Strona główna Perun Tac: dwie dywizje obok siebie, szkolenia i ochrona',
        href: 'https://peruntac.pl',
        linkLabel: 'Zobacz stronę',
      },
      {
        id: 'oboda-group',
        name: 'Oboda Group',
        sentence: 'Szkolenia dla gabinetów stomatologicznych ułożone według ról w zespole, nie według kategorii w cenniku.',
        tags: ['Redesign', 'Architektura oferty', 'Strona internetowa'],
        year: '2026',
        status: '[Etap 1, do potwierdzenia]',
        image: '/v2/work/oboda-group.webp',
        alt: 'Strona główna Oboda Group: żółte tło, hasło o szkoleniu rejestratorek i zdjęcie trenerki',
        href: '',
        linkLabel: '',
      },
      {
        id: 'tcc-global',
        name: 'TCC Global',
        sentence: 'Propozycja nowej strony dla globalnej firmy, przygotowana i przedstawiona zarządowi.',
        tags: ['Strona internetowa', 'Motion', 'Prezentacja'],
        year: '2026',
        status: 'Projekt koncepcyjny',
        image: '',
        alt: '',
        href: '',
        linkLabel: '',
      },
    ],
    all: 'Wszystkie realizacje',
  },
  services: {
    eyebrow: 'Co robimy',
    title: ['Od kierunku marki', 'do działającego rozwiązania.'],
    lead: 'Możemy zająć się jednym obszarem albo połączyć kilka w spójny projekt. Zakres dobieramy do tego, co naprawdę wymaga zmiany.',
    items: [
      { id: 'branding', name: 'Branding', title: 'Marka z własnym charakterem.', body: 'Porządkujemy to, co chcesz powiedzieć, komu i dlaczego warto cię wybrać. Przekładamy ten kierunek na identyfikację wizualną i zasady, z których można korzystać na co dzień.', scope: ['Strategia marki', 'Identyfikacja wizualna', 'System marki', 'Wytyczne'], object: 'skaner' },
      { id: 'web', name: 'Strony internetowe', title: 'Strona z jasno określonym zadaniem.', body: 'Projektujemy i wdrażamy strony, które pokazują wartość oferty i prowadzą użytkownika do kolejnego kroku. Od struktury i treści po interfejs, wdrożenie oraz integracje.', scope: ['UX/UI', 'Struktura i treści', 'Development', 'CMS', 'Integracje'], object: 'kostka' },
      { id: 'graphic', name: 'Projektowanie graficzne', title: 'Spójność w każdym formacie.', body: 'Rozwijamy język wizualny marki w prezentacjach, kampaniach, materiałach sprzedażowych i komunikacji digital. Tworzymy też szablony, z którymi twój zespół może pracować samodzielnie.', scope: ['Prezentacje', 'Materiały sprzedażowe', 'Kampanie', 'Social media', 'Szablony'], object: '' },
      { id: 'automation', name: 'Automatyzacje procesów', title: 'Mniej przeklejania. Więcej działania.', body: 'Łączymy narzędzia i porządkujemy powtarzalne zadania. Projektujemy przepływ informacji między formularzami, CRM, pocztą i innymi systemami używanymi w firmie.', scope: ['Analiza procesów', 'Integracje', 'Obieg informacji', 'Powiadomienia', 'Raportowanie'], object: 'przeplyw' },
      { id: 'ai', name: 'Rozwiązania AI', title: 'AI z konkretnym zadaniem.', body: 'Sprawdzamy, gdzie AI może wesprzeć pracę zespołu: w wyszukiwaniu wiedzy, analizie dokumentów czy przygotowaniu odpowiedzi. Zaczynamy od zastosowania i testów, nie od obietnicy, że AI zrobi wszystko.', scope: ['Analiza zastosowań', 'Prototypy', 'Asystenci wiedzy', 'Praca z dokumentami', 'Integracje'], object: 'siatka' },
    ],
  },
  about: {
    eyebrow: 'Studio',
    title: ['Myślimy całościowo.', 'Dopracowujemy szczegóły.'],
    body: [
      'Nest Studio to studio łączące branding, projektowanie cyfrowe i technologię.',
      'Interesuje nas nie tylko to, jak projekt wygląda w dniu prezentacji. Tak samo ważne jest to, jak działa po wdrożeniu: czy marka pozostaje spójna, czy stronę można rozwijać i czy zespół potrafi korzystać z nowych narzędzi. Dlatego łączymy decyzje projektowe z realiami codziennej pracy.',
    ],
    principles: [
      { title: 'Najpierw zrozumienie', body: 'Nie zaczynamy od gotowej odpowiedzi. Najpierw poznajemy kontekst i ograniczenia.' },
      { title: 'Decyzje z uzasadnieniem', body: 'Pokazujemy nie tylko rozwiązanie, ale też powód, dla którego je proponujemy.' },
      { title: 'Całość i detal', body: 'Pilnujemy wspólnego kierunku, nie tracąc z oczu pojedynczego widoku, zdania czy interakcji.' },
    ],
    link: 'Porozmawiajmy o projekcie',
  },
  testimonials: {
    eyebrow: 'Opinie',
    items: [
      { quote: '[Autentyczna wypowiedź klienta opisująca konkretną zmianę lub doświadczenie współpracy.]', name: '[Imię i nazwisko]', role: '[Stanowisko, firma]', placeholder: true },
    ],
  },
  team: {
    eyebrow: 'Zespół',
    title: ['Za projektem', 'stoją konkretni ludzie.'],
    lead: 'Pracujesz bezpośrednio z osobą, która prowadzi projekt. Przy większych zakresach dołączają sprawdzeni specjaliści.',
    people: [
      { name: 'Filip Jakubiak', role: 'Założyciel. Branding, strony, automatyzacje', bio: `Projektuje od ${FOUNDED_YEAR} roku. [Dwa konkretne zdania o odpowiedzialności i doświadczeniu.]`, placeholder: true },
      { name: '[Imię i nazwisko]', role: '[Rola specjalisty]', bio: '[Dwa konkretne zdania o odpowiedzialności i doświadczeniu.]', placeholder: true },
    ],
  },
  process: {
    eyebrow: 'Jak pracujemy',
    title: ['Jasny kierunek.', 'Przemyślane decyzje.'],
    intro: 'Wiesz, nad czym pracujemy, co wymaga twojej decyzji i co wydarzy się dalej.',
    outcomeLabel: 'Efekt etapu',
    steps: [
      { title: 'Zrozumienie', body: 'Zaczynamy od firmy, odbiorców i celu projektu. Sprawdzamy, co już działa, co przeszkadza i jaki efekt będzie oznaczał dobrze wykonaną pracę.', outcome: 'Uzgodniony cel, priorytety i zakres.' },
      { title: 'Kierunek', body: 'Układamy strukturę rozwiązania. W zależności od projektu: strategię marki, architekturę strony lub mapę procesu. Ustalamy fundamenty, zanim przejdziemy do szczegółów.', outcome: 'Zaakceptowany kierunek i plan realizacji.' },
      { title: 'Projekt i wdrożenie', body: 'Projektujemy, pokazujemy kolejne etapy i zbieramy feedback. Następnie wdrażamy rozwiązanie i sprawdzamy je w uzgodnionych scenariuszach użycia.', outcome: 'Gotowe i przetestowane rozwiązanie.' },
      { title: 'Przekazanie i rozwój', body: 'Przekazujemy materiały, dostęp i instrukcje objęte zakresem. Ustalamy, co warto obserwować po uruchomieniu i jak może wyglądać dalsze wsparcie.', outcome: 'Jasny sposób korzystania z rozwiązania i plan kolejnych kroków.' },
    ],
  },
  pricing: {
    eyebrow: 'Wycena',
    title: ['Koszt wynika', 'z zakresu.'],
    lead: 'Wycenę przygotowujemy po ustaleniu celu i zakresu. Przed rozpoczęciem otrzymujesz opis prac i koszt realizacji.',
    tiers: [
      { name: 'Marka', price: '[od 0 000 zł]', body: 'Kierunek marki i identyfikacja wizualna z zasadami użycia.', scope: ['Strategia marki', 'Identyfikacja', 'Wytyczne'] },
      { name: 'Strona', price: '[od 0 000 zł]', body: 'Projekt i wdrożenie strony z treściami, CMS i integracjami.', scope: ['Struktura i treści', 'UX/UI', 'Wdrożenie'] },
      { name: 'Marka, strona i procesy', price: '[wycena indywidualna]', body: 'Całość: od kierunku marki po automatyzację obsługi zapytań.', scope: ['Branding', 'Strona', 'Automatyzacje i AI'] },
    ],
    note: 'Znaczenie mają między innymi liczba materiałów lub widoków, poziom złożoności, integracje i zakres wdrożenia.',
    faqTitle: 'Zanim zaczniemy.',
    faq: [
      { q: 'Czy muszę wiedzieć dokładnie, czego potrzebuję?', a: 'Nie. Możesz przyjść z gotowym briefem albo opisać sytuację, którą chcesz zmienić. Na początku ustalimy, czy potrzebujesz nowej identyfikacji, strony, uporządkowania procesu czy połączenia kilku działań.' },
      { q: 'Czy mogę zamówić tylko jedną usługę?', a: 'Tak. Możemy zaprojektować samą stronę, rozwinąć istniejącą identyfikację albo zautomatyzować wybrany proces. Nie każdy projekt wymaga zmiany wszystkiego.' },
      { q: 'Ile kosztuje współpraca?', a: 'Wycenę przygotowujemy po ustaleniu celu i zakresu. Znaczenie mają między innymi liczba materiałów lub widoków, poziom złożoności, integracje i zakres wdrożenia. Przed rozpoczęciem otrzymujesz opis prac i koszt realizacji.' },
      { q: 'Jak długo trwa projekt?', a: 'Harmonogram zależy od zakresu, dostępności materiałów i liczby etapów decyzyjnych. Termin ustalamy przed rozpoczęciem, z uwzględnieniem czasu na feedback, testy i przygotowanie do publikacji.' },
      { q: 'Czy pracujecie z istniejącą identyfikacją lub stroną?', a: 'Tak. Najpierw sprawdzamy, co warto zachować. Możemy rozwinąć obecny system, uporządkować wybrane elementy albo zaproponować większą zmianę, jeśli będzie uzasadniona.' },
      { q: 'Co otrzymam po zakończeniu?', a: 'Materiały i dostęp określone w zakresie projektu. W zależności od usługi mogą to być pliki identyfikacji, wytyczne, szablony, wdrożona strona, dokumentacja integracji i instrukcja obsługi. Warunki praw, licencji i przekazania ustalamy przed rozpoczęciem.' },
      { q: 'Czy każde usprawnienie wymaga AI?', a: 'Nie. Najpierw przyglądamy się zadaniu. Jeśli wystarczy prostsza integracja lub automatyzacja oparta na regułach, proponujemy właśnie takie rozwiązanie.' },
      { q: 'Czy możecie wspierać nas po wdrożeniu?', a: 'Możemy ustalić osobny zakres dalszego rozwoju, aktualizacji lub wsparcia. Jego warunki zależą od rozwiązania i potrzeb zespołu.' },
    ],
  },
  partners: {
    eyebrow: 'Zaufali nam',
    title: 'Firmy, z którymi pracujemy',
    names: ['Perun Tac', 'Perun Sec', 'Oboda Group', 'TCC Global', '[Klient]', '[Klient]'],
    note: 'Logotypy pokazujemy za zgodą klientów.',
  },
  cta: {
    title: ['Co chcesz zmienić', 'w swojej firmie?'],
    body: 'Wizerunek, stronę, sposób pracy, a może kilka rzeczy naraz? Opowiedz nam, gdzie jesteś i czego potrzebujesz. Od tego zaczniemy.',
    button: 'Porozmawiajmy o projekcie',
    mailPrefix: 'Wolisz mail? Napisz na',
  },
  contact: {
    eyebrow: 'Kontakt',
    title: ['Zacznijmy od tego,', 'czego potrzebujesz.'],
    lead: 'Opisz krótko firmę, pomysł lub problem. Nie potrzebujesz gotowej specyfikacji. Na tej podstawie ustalimy, jaki powinien być kolejny krok.',
    required: 'Pola oznaczone * są wymagane.',
    fields: {
      name: { label: 'Imię', hint: 'Jak mamy się do ciebie zwracać?' },
      email: { label: 'E-mail', hint: 'Na ten adres odpowiemy.' },
      message: { label: 'Opis projektu', hint: 'Co chcesz stworzyć lub zmienić? Co jest dziś największym wyzwaniem?' },
      company: { label: 'Firma lub obecna strona', hint: '' },
      scope: { label: 'Zakres', options: ['Branding', 'Strona', 'Grafika', 'Automatyzacje', 'AI', 'Jeszcze nie wiem'] },
      budget: { label: 'Planowany budżet', options: ['[przedział 1]', '[przedział 2]', '[przedział 3]', 'Potrzebuję pomocy w określeniu'] },
      timing: { label: 'Preferowany termin', hint: '' },
    },
    optional: 'opcjonalnie',
    submit: 'Wyślij zapytanie',
    privacy: 'Informacje o przetwarzaniu danych znajdziesz w Polityce prywatności.',
    nextTitle: 'Co dalej?',
    next: ['Zapoznamy się z wiadomością.', 'Wrócimy z pytaniami lub propozycją rozmowy.', 'Jeśli zakres będzie pasował do naszych kompetencji, ustalimy sposób przygotowania oferty.'],
    sentTitle: 'Otwieramy twoją pocztę.',
    sentBody: `Wiadomość jest gotowa do wysłania w twoim programie pocztowym. Jeśli nic się nie otworzyło, napisz na ${EMAIL}.`,
    mailSubject: 'Zapytanie ze strony Nest Studio',
  },
  footer: {
    tagline: ['Branding, strony i technologia.', 'Splecione w jedną całość.'],
    cols: [
      { title: 'Odkrywaj', links: [{ label: 'Realizacje', href: '#realizacje' }, { label: 'Usługi', href: '#uslugi' }, { label: 'Studio', href: '#studio' }, { label: 'Kontakt', href: '#kontakt' }] },
      { title: 'Usługi', links: [{ label: 'Branding', href: '#uslugi' }, { label: 'Strony internetowe', href: '#uslugi' }, { label: 'Projektowanie graficzne', href: '#uslugi' }, { label: 'Automatyzacje', href: '#uslugi' }, { label: 'AI', href: '#uslugi' }] },
    ],
    contactTitle: 'Kontakt',
    socialTitle: 'Profile',
    legal: '[Pełna nazwa podmiotu]',
    privacy: 'Polityka prywatności',
    top: 'Na górę',
  },
};

export const pl = polishTypography(raw);
