import type { Content } from './types';

export const pl: Content = {
  lang: 'pl',
  meta: {
    title: 'Nest Studio: branding, strony www i automatyzacje AI',
    description: 'Studio projektowe Filipa Jakubiaka, od 2014. Strategia marki, identyfikacja, strony www i automatyzacje AI w jednej pracowni.',
    ogTitle: 'Wyglądaj na tyle, ile jesteś wart.',
  },
  nav: {
    links: [
      { label: 'Projekty', href: '#projekty' },
      { label: 'Usługi', href: '#uslugi' },
      { label: 'Proces', href: '#proces' },
      { label: 'Studio', href: '#studio' },
      { label: 'Kontakt', href: '#kontakt' },
    ],
    cta: 'Rozpocznij projekt',
    langLabel: 'Zmień język',
    menu: 'Menu',
    closeMenu: 'Zamknij menu',
    remote: 'Zdalnie, z Polski',
  },
  preloader: { loading: 'Ładowanie strony' },
  hero: {
    eyebrow: 'Studio projektowe, od 2014',
    lines: ['Projektujemy marki,', 'które wyglądają', 'na tyle, ile są warte.'],
    dropAfterLine: 1,
    lead: 'Strategia, identyfikacja, strona i automatyzacje AI. Jedna pracownia, jedna struktura.',
    ctaPrimary: 'Rozpocznij projekt',
    ctaSecondary: 'Zobacz projekty',
  },
  tension: {
    title: 'Większość firm wygląda słabiej, niż jest.',
    leftLabel: 'jak wyglądasz',
    leftWord: 'Widoczność',
    rightLabel: 'ile jesteś wart',
    rightWord: 'Wartość',
    you: 'Twoja pewnie też. Tę lukę da się domknąć.',
    body: 'Luka między tym, jak firma wygląda, a tym, ile jest warta, kosztuje: zaufanie, ceny, czas rozmów. Domykamy ją strategią, identyfikacją, stroną i maszynownią, która robi robotę za ciebie.',
    closing: ['Nie egzekucja.', 'Nie osobne usługi.', 'Jedna struktura.'],
  },
  showreel: {
    eyebrow: 'Showreel, renderowany na żywo',
    title: 'To nie jest film.',
    lead: 'Ten reel renderuje się na żywo z tej samej sceny, na której stoi strona. Scroll jest jego suwakiem.',
    cuts: [
      { label: 'Typografia', line: 'Typografia gra rolę obrazu.' },
      { label: 'Chrom', line: 'Metal, który się nie zatrzymuje.' },
      { label: 'Nici', line: 'Tysiące nici. Jeden splot.' },
      { label: 'Web', line: 'Strony, które są dowodem.' },
      { label: 'Automatyzacje', line: 'Maszynownia, którą widać.' },
    ],
    play: 'Odtwórz',
    pause: 'Zatrzymaj',
    playAria: 'Odtwórz showreel',
    pauseAria: 'Zatrzymaj showreel',
  },
  projects: {
    title: 'Wybrane projekty',
    lead: 'Metryka na pierwszym planie. Pełne case study na życzenie.',
    askLink: 'Poproś o pełne case study',
    items: [
      { slug: 'perun-tac', name: 'Perun Tac', scope: ['Branding', 'Strona', 'CMS'], metric: 'metryka do uzupełnienia', metricLabel: 'wynik po akceptacji', year: 'rok', summary: 'Identyfikacja, strona i CMS dla marki wyposażenia taktycznego.', seed: 11, placeholder: true },
      { slug: 'tcc-global', name: 'TCC Global', scope: ['Strona'], metric: 'metryka do uzupełnienia', metricLabel: 'wynik po akceptacji', year: 'rok', summary: 'Strona dla firmy szkoleniowo-doradczej.', seed: 23, placeholder: true },
      { slug: 'oboda-group', name: 'Oboda Group', scope: ['Redesign'], metric: 'metryka do uzupełnienia', metricLabel: 'wynik po akceptacji', year: 'rok', summary: 'Redesign strony grupy.', seed: 37, placeholder: true },
    ],
  },
  services: {
    eyebrow: 'Usługi',
    title: 'Cztery nici. Jedna struktura.',
    items: [
      { id: 'strategy', title: 'Strategia marki', body: 'Pozycjonowanie, komunikacja, architektura marki. Zanim cokolwiek narysujemy, wiemy, po co i dla kogo.' },
      { id: 'brand', title: 'Branding', body: 'Znak, typografia, kolor, zasady i pliki. System, którego twój zespół użyje od pierwszego dnia.' },
      { id: 'web', title: 'Strony www', body: 'Projekt i kod. Szybkie, dostępne, z ruchem, który coś znaczy. Taka jak ta.' },
      { id: 'ai', title: 'AI i automatyzacje', body: 'Wdrożenia AI i automatyzacje procesów: zapytania, oferty, faktury, obsługa. Maszynownia, którą widać w działaniu.' },
    ],
    note: 'Możesz wziąć jedną nić. Najlepiej działają splecione.',
  },
  aiDemo: {
    title: 'Automatyzacja, którą widać.',
    lead: 'Wybierz proces, który dziś robisz ręcznie. Przepływ złoży się sam.',
    run: 'Uruchom przepływ',
    status: { ready: 'Gotowe', running: 'Pracuje', done: 'Zakończone' },
    note: 'Demo działa na przykładowych danych. We wdrożeniu łączymy przepływ z twoimi narzędziami.',
    nodeLabels: { trigger: 'Wyzwalacz', read: 'Odczyt', classify: 'Klasyfikacja', draft: 'Wersja robocza', review: 'Sprawdzenie', crm: 'CRM', email: 'E-mail', document: 'Dokument', calendar: 'Kalendarz', notify: 'Powiadomienie' },
    logAria: 'Dziennik przepływu',
    presets: [
      { id: 'inquiry', label: 'Zapytanie z formularza', steps: [
        { node: 'trigger', text: 'Nowe zgłoszenie z formularza' },
        { node: 'classify', text: 'Klasyfikacja: oferta, wsparcie, spam' },
        { node: 'crm', text: 'Wpis do CRM z podsumowaniem' },
        { node: 'draft', text: 'Wersja robocza odpowiedzi w twoim tonie' },
        { node: 'notify', text: 'Powiadomienie z jednym przyciskiem: wyślij' },
      ] },
      { id: 'invoice', label: 'Nowa faktura', steps: [
        { node: 'trigger', text: 'Faktura z e-maila lub skrzynki' },
        { node: 'read', text: 'Odczyt danych: kontrahent, kwota, termin' },
        { node: 'review', text: 'Dopasowanie do zamówienia' },
        { node: 'document', text: 'Wpis do księgowości' },
        { node: 'calendar', text: 'Przypomnienie przed terminem' },
      ] },
      { id: 'proposal', label: 'Oferta dla klienta', steps: [
        { node: 'trigger', text: 'Notatka ze spotkania' },
        { node: 'read', text: 'Wyciągnięcie zakresu i założeń' },
        { node: 'draft', text: 'Wersja robocza oferty z twojego szablonu' },
        { node: 'review', text: 'Sprawdzenie cen i terminów' },
        { node: 'document', text: 'Dokument do twojej akceptacji' },
      ] },
      { id: 'social', label: 'Wpis do social mediów', steps: [
        { node: 'trigger', text: 'Nowy projekt w portfolio' },
        { node: 'draft', text: 'Trzy wersje wpisu w tonie marki' },
        { node: 'read', text: 'Dobór grafiki z systemu' },
        { node: 'calendar', text: 'Kolejka publikacji' },
        { node: 'notify', text: 'Raport po tygodniu' },
      ] },
    ],
  },
  process: {
    title: 'Jak to wygląda',
    steps: [
      { title: 'Rozmowa', body: 'Godzina o tym, co robisz, dla kogo i co dziś robisz ręcznie. Po niej dostajesz zakres i wycenę.' },
      { title: 'Strategia', body: 'Pozycjonowanie, komunikacja, architektura. Krótki dokument, który potem trzyma wszystko w ryzach.' },
      { title: 'Projekt', body: 'Identyfikacja i projekt strony. Pokazujemy kierunki, wybieramy jeden, dopracowujemy.' },
      { title: 'Budowa', body: 'Kod, treści, wdrożenie. Szybko, dostępnie, z ruchem, który coś znaczy.' },
      { title: 'Maszynownia', body: 'Automatyzacje i AI podpięte do twoich narzędzi. Uruchamiamy, uczymy zespół, zostajemy na wsparcie.' },
    ],
  },
  studio: {
    title: 'Za studiem stoi Filip Jakubiak.',
    p1: 'Projektuję od 2014. Zaczynałem od identyfikacji, potem doszły strony, a od kilku lat automatyzacje i AI, bo marka bez maszynowni to tylko obrazek.',
    p2: 'Pracuję sam albo z małym zespołem dobranym do projektu. Rozmawiasz ze mną, nie z opiekunem klienta.',
    years: '{years} lat w branży',
    since: 'od 2014',
    photoAlt: 'Filip Jakubiak, Nest Studio',
    photoPlaceholder: 'zdjęcie',
  },
  faq: {
    title: 'Pytania, które padają najczęściej',
    items: [
      { q: 'Ile kosztuje projekt?', a: 'Zależy od zakresu. Identyfikacja, strona i automatyzacje to trzy różne budżety, ale jedna wycena po rozmowie. Wyceniamy zakres, nie godziny.' },
      { q: 'Ile to trwa?', a: 'Identyfikacja zwykle tygodnie, strona od kilku tygodni do kilku miesięcy, automatyzacje często dni. Harmonogram ustalamy przed startem i go trzymamy.' },
      { q: 'Mogę zamówić tylko stronę albo tylko automatyzację?', a: 'Tak. Każda nić działa osobno. Najlepiej działają splecione, więc zawsze powiemy, co warto dołożyć, i uszanujemy, jeśli nie teraz.' },
      { q: 'Jak wygląda praca z AI w praktyce?', a: 'Zaczynamy od procesu, który robisz ręcznie. Budujemy przepływ na twoich narzędziach, testujemy na prawdziwych danych, uczymy zespół. AI robi robotę, człowiek akceptuje.' },
      { q: 'Co dostaję na koniec?', a: 'Pliki źródłowe, system marki, kod strony, dostępy, dokumentację przepływów i instrukcje. Wszystko jest twoje.' },
      { q: 'Czy moja strona będzie tak animowana jak ta?', a: 'Jeśli to służy marce. Ruch to narzędzie, nie ozdoba. Ta strona jest showreelem, twoja ma sprzedawać.' },
      { q: 'Gdzie pracujecie?', a: 'Zdalnie, z Polski, po polsku i po angielsku. Spotkania online, w razie potrzeby na miejscu.' },
    ],
  },
  contact: {
    eyebrow: 'Kontakt',
    title: 'Zbudujmy gniazdo dla twojej marki.',
    lead: 'Jedna rozmowa, bez prezentacji i bez zobowiązań. Opowiedz, co robisz ręcznie i jak chcesz wyglądać.',
    cta: 'Rozpocznij projekt',
    calendar: 'wybierz termin w kalendarzu',
    or: 'albo',
  },
  footer: {
    contact: 'Kontakt',
    data: 'Dane',
    social: 'Social',
    ask: 'Zapytaj o Nest Studio',
    askPrompt: 'Co wiesz o Nest Studio, studiu projektowym Filipa Jakubiaka (neststudio.pl)? Czym się zajmuje i co wyróżnia?',
    legal: 'Zaprojektowane i zbudowane w Nest Studio.',
    privacy: 'Polityka prywatności',
    country: 'Polska',
  },
  system: {
    skip: 'Przejdź do treści',
    rail: 'Nawigacja po sekcjach',
    reduced: 'Animacje wyłączone zgodnie z ustawieniami systemu.',
    noWebgl: 'Scena 3D niedostępna w tej przeglądarce. Treść działa bez niej.',
    notFound: 'Tej strony nie ma.',
    backHome: 'Wróć na stronę główną',
    placeholder: 'do uzupełnienia',
  },
};
