import type { Content } from './types';
import { polishTypography } from './typography';

/* Teksty PL (język główny). Strategia, łuk narracji i uzasadnienia: docs/copy.md. */
export const pl: Content = polishTypography<Content>({
  lang: 'pl',
  meta: {
    title: 'Nest Studio: branding, strony www i automatyzacje AI',
    description: 'Studio projektowe Filipa Jakubiaka, od 2014. Strategia marki, identyfikacja, strony www i automatyzacje AI z jednej pracowni, więc nic nie wisi luzem.',
    ogTitle: 'Projektujemy marki i budujemy wszystko, co je trzyma.',
  },
  nav: {
    links: [
      { label: 'Projekty', href: '#projekty' },
      { label: 'Usługi', href: '#uslugi' },
      { label: 'Proces', href: '#proces' },
      { label: 'Studio', href: '#studio' },
      { label: 'Kontakt', href: '#kontakt' },
    ],
    cta: 'Rozpocznij projekt',
    langLabel: 'Zmień język',
    menu: 'Menu',
    closeMenu: 'Zamknij menu',
    remote: 'Zdalnie, z Polski',
  },
  preloader: { loading: 'Ładowanie strony' },
  hero: {
    eyebrow: 'Studio projektowe, od 2014',
    lines: ['Projektujemy marki', 'i budujemy wszystko,', 'co je trzyma.'],
    dropAfterLine: 1,
    lead: 'Strategia, identyfikacja, strona i automatyzacje AI z jednej pracowni. Nic nie wisi luzem.',
    ctaPrimary: 'Rozpocznij projekt',
    ctaSecondary: 'Zobacz projekty',
  },
  tension: {
    title: 'Firma urosła. Wizerunek nie.',
    leftLabel: 'jak cię widzą',
    leftWord: 'Wygląd',
    rightLabel: 'ile jesteś wart',
    rightWord: 'Wartość',
    you: 'Logo z pierwszego roku. Strona sprzed trzech lat. Oferty w Wordzie.',
    body: 'Każdą część robił ktoś inny i w innym czasie, więc nic do siebie nie pasuje. Klient widzi to, zanim przeczyta ofertę. Ta luka kosztuje: zaufanie, stawki i godziny tłumaczenia, kim jesteś.',
    closing: ['Luźne nici się rwą.', 'Splecione trzymają.'],
  },
  showreel: {
    eyebrow: 'Showreel, renderowany na żywo',
    title: 'To nie jest film.',
    lead: 'Wszystko, co tu widzisz, powstaje na żywo w twojej przeglądarce. Scroll jest suwakiem.',
    cuts: [
      { label: 'Typografia', line: 'Litery zamiast zdjęć.' },
      { label: 'Chrom', line: 'Metal, który nie stygnie.' },
      { label: 'Nici', line: 'Z chaosu w splot.' },
      { label: 'Web', line: 'Strona jest dowodem.' },
      { label: 'Automatyzacje', line: 'Maszynownia, którą widać.' },
    ],
    play: 'Odtwórz',
    pause: 'Zatrzymaj',
    playAria: 'Odtwórz showreel',
    pauseAria: 'Zatrzymaj showreel',
  },
  projects: {
    title: 'Wybrane projekty',
    lead: 'Co było do zrobienia i co zrobiliśmy. Pełne case study pokażemy na rozmowie.',
    askLink: 'Poproś o pełne case study',
    items: [
      { slug: 'perun-tac', name: 'Perun Tac', scope: ['Branding', 'Strona', 'CMS'], metric: '3', metricLabel: 'redaktorów prowadzi stronę z własnego panelu', year: '2026', summary: 'Szkolenia strzeleckie i taktyczne z Wrocławia. Strona w dwóch językach i panel, w którym zespół sam publikuje szkolenia i terminy.', seed: 11, placeholder: true },
      { slug: 'tcc-global', name: 'TCC Global', scope: ['Strona', 'Motion'], metric: '2', metricLabel: 'kierunki nowej strony do wyboru', year: '2026', summary: 'Programy lojalnościowe dla sieci handlowych i marek. Nowa strona opowiedziana ruchem, w dwóch kierunkach do decyzji zarządu.', seed: 23, placeholder: true },
      { slug: 'oboda-group', name: 'Oboda Group', scope: ['Redesign', 'Architektura treści'], metric: '9 → 5', metricLabel: 'kategorii zamienionych na ścieżki według roli', year: '2026', summary: 'Szkolenia i doradztwo dla stomatologii. Koncepcja nowej strony, na której lekarz, asystentka i właściciel gabinetu od razu trafiają do swojej oferty.', seed: 37, placeholder: true },
    ],
  },
  services: {
    eyebrow: 'Usługi',
    title: 'Cztery nici. Jeden splot.',
    items: [
      { id: 'strategy', title: 'Strategia marki', body: 'Pozycjonowanie, komunikacja, architektura marki. Ustalamy, co mówisz, komu i dlaczego właśnie ty. Dopiero potem rysujemy.' },
      { id: 'brand', title: 'Branding', body: 'Znak, typografia, kolor, zasady i gotowe pliki. System, z którego twój zespół korzysta od pierwszego dnia, bez dzwonienia do nas.' },
      { id: 'web', title: 'Strony www', body: 'Projekt i kod z jednej ręki. Szybkie, dostępne, z ruchem tylko tam, gdzie coś wyjaśnia. Ta strona jest próbką.' },
      { id: 'ai', title: 'AI i automatyzacje', body: 'Zapytania, oferty, faktury, obsługa klienta. Przepływy AI podpięte do narzędzi, których już używasz. Człowiek zatwierdza, maszyna robi resztę.' },
    ],
    note: 'Każdą nić można wziąć osobno. Najmocniej trzymają splecione.',
  },
  aiDemo: {
    title: 'Automatyzacja, którą widać.',
    lead: 'Wybierz proces, który dziś ktoś u ciebie robi ręcznie, i uruchom przepływ.',
    run: 'Uruchom przepływ',
    status: { ready: 'Gotowe', running: 'Pracuje', done: 'Zakończone' },
    note: 'Demo działa na przykładowych danych. Przy wdrożeniu podpinamy przepływ pod twoje narzędzia.',
    nodeLabels: { trigger: 'Wyzwalacz', read: 'Odczyt', classify: 'Klasyfikacja', draft: 'Wersja robocza', review: 'Sprawdzenie', crm: 'CRM', email: 'E-mail', document: 'Dokument', calendar: 'Kalendarz', notify: 'Powiadomienie' },
    logAria: 'Dziennik przepływu',
    presets: [
      { id: 'inquiry', label: 'Zapytanie z formularza', steps: [
        { node: 'trigger', text: 'Nowe zgłoszenie z formularza' },
        { node: 'classify', text: 'Klasyfikacja: oferta, wsparcie, spam' },
        { node: 'crm', text: 'Wpis do CRM z krótkim podsumowaniem' },
        { node: 'draft', text: 'Szkic odpowiedzi w tonie twojej marki' },
        { node: 'notify', text: 'Powiadomienie z jednym przyciskiem: wyślij' },
      ] },
      { id: 'invoice', label: 'Nowa faktura', steps: [
        { node: 'trigger', text: 'Faktura przychodzi mailem' },
        { node: 'read', text: 'Odczyt danych: kontrahent, kwota, termin' },
        { node: 'review', text: 'Dopasowanie do zamówienia' },
        { node: 'document', text: 'Wpis do księgowości' },
        { node: 'calendar', text: 'Przypomnienie przed terminem płatności' },
      ] },
      { id: 'proposal', label: 'Oferta dla klienta', steps: [
        { node: 'trigger', text: 'Notatka ze spotkania' },
        { node: 'read', text: 'Zakres i założenia wyciągnięte z notatki' },
        { node: 'draft', text: 'Szkic oferty na twoim szablonie' },
        { node: 'review', text: 'Kontrola cen i terminów' },
        { node: 'document', text: 'Dokument czeka na twoją akceptację' },
      ] },
      { id: 'social', label: 'Post w social mediach', steps: [
        { node: 'trigger', text: 'Nowy projekt w portfolio' },
        { node: 'draft', text: 'Trzy wersje wpisu w tonie marki' },
        { node: 'read', text: 'Grafika dobrana z systemu marki' },
        { node: 'calendar', text: 'Wpis trafia do kolejki publikacji' },
        { node: 'notify', text: 'Podsumowanie wyników po tygodniu' },
      ] },
    ],
  },
  process: {
    title: 'Jedna nić, pięć etapów.',
    steps: [
      { title: 'Rozmowa', body: 'O firmie, klientach i o tym, co dziś zjada najwięcej czasu. Po niej dostajesz zakres i wycenę na piśmie.' },
      { title: 'Strategia', body: 'Pozycjonowanie i komunikacja spisane na kilku stronach. Ten dokument rozstrzyga potem każdy spór o kolor i słowo.' },
      { title: 'Projekt', body: 'Identyfikacja i projekt strony. Pokazujemy kierunki, wybieramy jeden i dopracowujemy go razem z tobą.' },
      { title: 'Budowa', body: 'Kod, treści, wdrożenie. Strona powstaje tam, gdzie ją zaprojektowano, więc nic nie ginie przy przekazaniu.' },
      { title: 'Maszynownia', body: 'Automatyzacje i AI podpięte do twoich narzędzi. Uruchamiamy je, uczymy zespół i zostajemy na wsparcie.' },
    ],
  },
  studio: {
    title: 'Rozmawiasz z tym, kto zrobi robotę.',
    p1: 'Jestem Filip Jakubiak, projektuję od 2014 roku. Zaczynałem od identyfikacji, potem doszły strony, a dziś także automatyzacje i AI. Robię je razem, bo osobno się rozjeżdżają.',
    p2: 'Pracuję sam albo z małym zespołem dobranym do projektu. Nie ma opiekuna klienta ani briefu podawanego dalej. Kto z tobą rozmawia, ten projektuje.',
    years: '{years} lat w branży',
    since: 'od 2014',
    photoAlt: 'Filip Jakubiak, Nest Studio',
    photoPlaceholder: 'zdjęcie',
  },
  faq: {
    title: 'Zanim napiszesz',
    items: [
      { q: 'Ile kosztuje projekt?', a: 'Tyle, ile wynika z zakresu, dlatego wycenę podajemy po pierwszej rozmowie, na piśmie. Jedna wycena obejmuje wszystko, co ustalimy: strategię, identyfikację, stronę i automatyzacje.' },
      { q: 'Ile to trwa?', a: 'To też zależy od zakresu. Harmonogram z konkretnymi datami dostajesz razem z wyceną, zanim cokolwiek zaczniemy.' },
      { q: 'Po co mi jedna pracownia, skoro mam grafika i programistę?', a: 'Bo najwięcej psuje się na styku. Grafik oddaje pliki, programista robi po swojemu, automatyzacje dokłada ktoś trzeci. Kiedy całość powstaje w jednym miejscu, nie ma czego zgubić przy przekazaniu.' },
      { q: 'Mogę zamówić tylko stronę albo tylko automatyzację?', a: 'Tak. Każdą nić można wziąć osobno. Powiemy, co jeszcze warto dołożyć, i przyjmiemy odpowiedź „nie teraz”.' },
      { q: 'Jak wygląda praca z AI w praktyce?', a: 'Zaczynamy od jednego procesu, który dziś zabiera najwięcej czasu. Budujemy przepływ na narzędziach, których już używasz, testujemy go na prawdziwych przykładach i uczymy zespół. AI przygotowuje, człowiek zatwierdza.' },
      { q: 'Co dostaję na koniec?', a: 'Pliki źródłowe, system marki, kod strony, dostępy i opis każdego przepływu. Wszystko należy do ciebie.' },
      { q: 'Czy moja strona będzie tak animowana jak ta?', a: 'Tylko tam, gdzie ruch coś wyjaśnia. Ta strona jest pokazem możliwości. Twoja ma przede wszystkim sprzedawać.' },
      { q: 'Gdzie pracujecie?', a: 'Zdalnie, z Polski, po polsku i po angielsku. Spotykamy się online, a na miejscu wtedy, gdy projekt tego wymaga.' },
    ],
  },
  contact: {
    eyebrow: 'Kontakt',
    title: 'Zacznijmy od pierwszej nici.',
    lead: 'Jedna rozmowa, bez prezentacji i bez zobowiązań. Opowiedz, czym zajmuje się twoja firma i co dziś robicie ręcznie. Resztę ułożymy razem.',
    cta: 'Rozpocznij projekt',
    calendar: 'wybierz termin w kalendarzu',
    or: 'albo',
  },
  footer: {
    contact: 'Kontakt',
    data: 'Dane',
    social: 'Social',
    ask: 'Zapytaj o Nest Studio',
    askPrompt: 'Co wiesz o Nest Studio, studiu projektowym Filipa Jakubiaka (neststudio.pl)? Czym się zajmuje, dla kogo pracuje i co je wyróżnia?',
    legal: 'Zaprojektowane i zbudowane w Nest Studio.',
    privacy: 'Polityka prywatności',
    country: 'Polska',
  },
  system: {
    skip: 'Przejdź do treści',
    rail: 'Nawigacja po sekcjach',
    reduced: 'Animacje wyłączone zgodnie z ustawieniami systemu.',
    noWebgl: 'Scena 3D nie działa w tej przeglądarce. Cała treść jest dostępna bez niej.',
    notFound: 'Tej strony nie ma.',
    backHome: 'Wróć na stronę główną',
    placeholder: 'do uzupełnienia',
  },
});
